# .github/workflows/test-build.yml
name: Test Build

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          VITE_BASE_URL: /build-test/
      
      - name: Test build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          
          if [ ! -f "dist/index.html" ]; then
            echo "Build issue: dist/index.html not found"
            exit 1
          fi
          
          JS_FILES=$(find dist -name "*.js" | wc -l)
          if [ "$JS_FILES" -eq "0" ]; then
            echo "Build issue: No JavaScript files found in dist"
            exit 1
          fi
          
          echo "Build verification successful!"